# Generated by Django 6.0.5 on 2026-05-17 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repuestos', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_inventario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_puntos', models.FloatField(default=0.0, editable=False)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado_oferta', models.BooleanField(default=True)),
                ('rango_horario', models.CharField(help_text='Ej: Lunes a Viernes 8am-4pm', max_length=200)),
                ('referencia_ubicacion', models.TextField(help_text='Indicaciones para el encuentro')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='repuestos.repuesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ofertas.oferta')),
            ],
        ),
        migrations.CreateModel(
            name='MatrizCompatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.repuesto')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
            options={
                'unique_together': {('repuesto', 'vehiculo')},
            },
        ),
    ]
