# Generated by Django 6.0.5 on 2026-07-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ofertas.oferta'),
        ),
        migrations.AddField(
            model_name='urgencia',
            name='vecino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.vecino', verbose_name='Vecino Afectado'),
        ),
        migrations.AddField(
            model_name='urgencia',
            name='vecino_postulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgencias_postuladas', to='usuarios.vecino'),
        ),
        migrations.AddField(
            model_name='urgencia',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo', verbose_name='Vehículo Accidentado'),
        ),
        migrations.AlterUniqueTogether(
            name='matrizcompatibilidad',
            unique_together={('repuesto', 'vehiculo')},
        ),
    ]
