# Generated by Django 6.0.5 on 2026-05-10 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ofertas.oferta'),
        ),
        migrations.AlterUniqueTogether(
            name='matrizcompatibilidad',
            unique_together={('repuesto', 'vehiculo')},
        ),
    ]
