# Generated by Django 6.0.5 on 2026-06-27 04:21

import apps.ofertas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={'verbose_name': 'Fotografía', 'verbose_name_plural': 'Fotografías'},
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='imagen',
            field=models.FileField(default='', help_text='Solo se admiten archivos JPG o PNG.', upload_to='ofertas/fotografias/', validators=[apps.ofertas.models.validar_extension_imagen]),
            preserve_default=False,
        ),
    ]
