# Generated by Django 5.2.15 on 2026-06-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_alter_fotografia_id_alter_matrizcompatibilidad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='tipo_tasacion',
            field=models.CharField(choices=[('algoritmico', 'Tasación Automática'), ('directo', 'Intercambio Directo'), ('tiempo', 'Banco de Tiempo')], default='algoritmico', max_length=20),
        ),
    ]
