# Generated by Django 5.2.15 on 2026-06-21 21:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_oferta_tipo_tasacion'),
        ('usuarios', '0002_alter_admin_id_alter_usuario_id_alter_vecino_id'),
        ('vehiculos', '0002_alter_vehiculo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgencia',
            fields=[
                ('id_urgencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pieza_requerida', models.CharField(max_length=150, verbose_name='Pieza Necesitada')),
                ('descripcion_contexto', models.TextField(verbose_name='Descripción del Contexto / Situación')),
                ('fecha_hora_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Publicación')),
                ('puntos_recompensa_extra', models.FloatField(verbose_name='Puntos de Recompensa Extra')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Sigue Activa?')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.vecino', verbose_name='Vecino Afectado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo', verbose_name='Vehículo Accidentado')),
            ],
        ),
    ]
