# Generated by Django 5.2.15 on 2026-07-08 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_urgencia'),
        ('usuarios', '0002_alter_admin_id_alter_usuario_id_alter_vecino_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencia',
            name='estado_tramite',
            field=models.CharField(choices=[('libre', 'Libre'), ('revision', 'En Revisión'), ('completada', 'Completada')], default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='urgencia',
            name='vecino_postulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgencias_postuladas', to='usuarios.vecino'),
        ),
    ]
