# Generated by Django 6.0.5 on 2026-07-08 22:37

import apps.ofertas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0005_urgencia_estado_tramite_urgencia_vecino_postulado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='imagen',
            field=models.FileField(blank=True, help_text='Solo se admiten archivos JPG o PNG.', null=True, upload_to='ofertas/fotografias/', validators=[apps.ofertas.models.validar_extension_imagen]),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matrizcompatibilidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
