# Generated by Django 5.2.15 on 2026-07-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_remove_fotografia_url_imagen_fotografia_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matrizcompatibilidad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
