# Generated by Django 6.0.5 on 2026-07-10 21:22

import apps.ofertas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_remove_fotografia_url_imagen_fotografia_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='imagen',
            field=models.FileField(blank=True, help_text='Solo se admiten archivos JPG o PNG, máximo 10MB.', null=True, upload_to='ofertas/fotografias/', validators=[apps.ofertas.models.validar_extension_imagen, apps.ofertas.models.validar_tamanio_imagen]),
        ),
    ]
