# Generated by Django 6.0.5 on 2026-07-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0007_alter_fotografia_id_alter_matrizcompatibilidad_id'),
        ('ofertas', '0007_alter_fotografia_imagen'),
    ]

    operations = [
    ]
