# Generated by Django 6.0.5 on 2026-05-10 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_intercambios', models.IntegerField(default=0)),
                ('es_inalterable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_exito', models.DateTimeField(auto_now_add=True)),
                ('puntos_transferidos', models.FloatField()),
                ('id_ofertante', models.CharField(max_length=100)),
                ('id_demandante', models.CharField(max_length=100)),
            ],
        ),
    ]
