# Generated by Django 6.0.5 on 2026-05-17 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_exito', models.DateTimeField(auto_now_add=True)),
                ('puntos_transferidos', models.FloatField()),
                ('demandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_como_demandante', to='usuarios.vecino')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='ofertas.oferta')),
                ('ofertante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_como_ofertante', to='usuarios.vecino')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'unique_together': {('oferta', 'ofertante', 'demandante')},
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_inalterable', models.BooleanField(default=True)),
                ('vecino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='usuarios.vecino')),
                ('transacciones', models.ManyToManyField(related_name='historiales', to='transacciones.transaccion')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
    ]
