# Generated by Django 6.0.5 on 2026-06-16 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
        ('transacciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdoIntercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('demandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acuerdos_como_demandante', to='usuarios.vecino')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acuerdos', to='ofertas.oferta')),
                ('ofertante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acuerdos_como_ofertante', to='usuarios.vecino')),
            ],
            options={
                'verbose_name': 'Acuerdo de Intercambio',
                'verbose_name_plural': 'Acuerdos de Intercambio',
                'unique_together': {('oferta', 'ofertante', 'demandante')},
            },
        ),
    ]
