# Generated by Django 6.0.5 on 2026-07-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0002_initial'),
        ('transacciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdointercambio',
            name='cancelacion_solicitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones_solicitadas', to='usuarios.vecino'),
        ),
        migrations.AddField(
            model_name='acuerdointercambio',
            name='demandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acuerdos_como_demandante', to='usuarios.vecino'),
        ),
        migrations.AddField(
            model_name='acuerdointercambio',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acuerdos', to='ofertas.oferta'),
        ),
        migrations.AddField(
            model_name='acuerdointercambio',
            name='ofertante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acuerdos_como_ofertante', to='usuarios.vecino'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='calificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_recibidas', to='usuarios.vecino'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='calificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_hechas', to='usuarios.vecino'),
        ),
        migrations.AddField(
            model_name='historial',
            name='vecino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='usuarios.vecino'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='acuerdo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='transacciones.acuerdointercambio'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='demandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_como_demandante', to='usuarios.vecino'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='ofertas.oferta'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ofertante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_como_ofertante', to='usuarios.vecino'),
        ),
        migrations.AddField(
            model_name='historial',
            name='transacciones',
            field=models.ManyToManyField(related_name='historiales', to='transacciones.transaccion'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='transacciones.transaccion'),
        ),
        migrations.AlterUniqueTogether(
            name='acuerdointercambio',
            unique_together={('oferta', 'ofertante', 'demandante')},
        ),
        migrations.AlterUniqueTogether(
            name='transaccion',
            unique_together={('oferta', 'ofertante', 'demandante')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('transaccion', 'calificador')},
        ),
    ]
