# Generated by Django 5.2.15 on 2026-06-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_acuerdointercambio'),
        ('transacciones', '0002_alter_historial_id'),
    ]

    operations = [
    ]
