# Generated by Django 5.2.15 on 2026-07-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_merge_0002_acuerdointercambio_0002_alter_historial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdointercambio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
