# Generated by Django 6.0.5 on 2026-07-10 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_alter_acuerdointercambio_id'),
        ('usuarios', '0003_alter_admin_id_alter_usuario_id_alter_vecino_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdointercambio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calificado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_recibidas', to='usuarios.vecino')),
                ('calificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_hechas', to='usuarios.vecino')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='transacciones.transaccion')),
            ],
            options={
                'unique_together': {('transaccion', 'calificador')},
            },
        ),
    ]
