# Generated by Django 6.0.5 on 2026-07-10 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_alter_acuerdointercambio_id_alter_historial_id_and_more'),
        ('usuarios', '0003_alter_admin_id_alter_usuario_id_alter_vecino_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdointercambio',
            name='cancelacion_solicitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones_solicitadas', to='usuarios.vecino'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
