# Generated by Django 6.0.5 on 2026-07-10 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0006_acuerdointercambio_cancelacion_solicitada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdointercambio',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='acuerdo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='transacciones.acuerdointercambio'),
        ),
    ]
