# Generated by Django 5.2.15 on 2026-07-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0007_acuerdointercambio_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdointercambio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
