# Generated by Django 6.0.5 on 2026-07-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0008_alter_acuerdointercambio_id_alter_historial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdointercambio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
