# Generated by Django 6.0.5 on 2026-05-10 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_inventario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_puntos', models.FloatField(default=0.0)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado_oferta', models.BooleanField(default=True)),
                ('rango_horario', models.CharField(max_length=200)),
                ('referencia_ubicacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id_repuesto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_pieza', models.CharField(max_length=100)),
                ('descripcion_tecnica', models.TextField()),
                ('estado_fisico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField()),
                ('orden', models.IntegerField()),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='productos.oferta')),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.repuesto'),
        ),
        migrations.CreateModel(
            name='MatrizCompatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.repuesto')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='repuesto',
            name='compatibilidad',
            field=models.ManyToManyField(through='productos.MatrizCompatibilidad', to='productos.vehiculo'),
        ),
    ]
