# Generated by Django 6.0.5 on 2026-05-22 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id_repuesto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_pieza', models.CharField(max_length=100)),
                ('descripcion_tecnica', models.TextField()),
                ('estado_fisico', models.CharField(max_length=50)),
                ('compatibilidad', models.ManyToManyField(related_name='repuestos', to='vehiculos.vehiculo')),
            ],
        ),
    ]
