# Generated by Django 6.0.5 on 2026-06-16 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('transacciones', '0002_acuerdointercambio'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='acuerdo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversacion', to='transacciones.acuerdointercambio'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.conversacion'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.vecino'),
        ),
    ]
