# Generated by Django 6.0.5 on 2026-06-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('sent', 'Enviado'), ('read', 'Leído'), ('error', 'Error')], default='sent', max_length=10),
        ),
    ]
